# The URL the site will be built for
base_url = "https://soberana.tv/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
# Whether external links are to be opened in a new tab

# If this is true, a `rel="noopener"` will always automatically be added for security reasons
external_links_target_blank = true

# CSS class to add to external links (e.g. "external-link")
external_links_class = "external-link"

[extra]
site_name = "Soberana"
opengraph_default = "images/opengraph-default.png"
opengraph_locale = "pt_BR"
